# Aufruf:
# pack build juergenzimmermann/buchweb:1.0.0 --builder paketobuildpacks/builder:base

# ------------------------------------------------------------------------------
# P r o j e c t   D e s c r i p t o r   f u e r   p a c k
# ------------------------------------------------------------------------------

# https://paketo.io/docs/buildpacks/language-family-buildpacks/nginx
# https://buildpacks.io/docs/app-developer-guide/using-project-descriptor
# https://buildpacks.io/docs/reference/config/project-descriptor
# https://github.com/buildpacks/spec/blob/main/extensions/project-descriptor.md
# https://buildpacks.io/docs/app-developer-guide/environment-variables
# https://console.cloud.google.com/gcr/images/paketo-buildpacks/GLOBAL/nginx

# [project]
id = "com.acme.kundeweb"
name = "Web Frontend fuer Microservice kunde"
version = "1.0.0"
authors = ["Juergen.Zimmermann@h-ka.de"]

[[project.licenses]]
type = "GPL-3.0"

[build]
# fuer Verzeichnis /workspace im Image
include = [
  "/dist",
  "/buildpack.yml",
  "/mime.types",
  "/nginx.conf",
  "/project.toml",
]

[[build.buildpacks]]
# https://console.cloud.google.com/gcr/images/paketo-buildpacks/GLOBAL/nginx
# https://github.com/paketo-buildpacks/nginx/tags
uri = "gcr.io/paketo-buildpacks/nginx:0.6.0"

[[build.env]]
# http://nginx.org/en/download.html
name = "BP_NGINX_VERSION"
value = "1.21.6"
