---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kundeweb
  labels:
    app: kundeweb
spec:
  selector:
    matchLabels:
      app: kundeweb
  replicas: 1
  template:
    metadata:
      labels:
        app: kundeweb
    spec:
      serviceAccountName: acme-kundeweb
      containers:
        - image: docker.io/juergenzimmermann/kundeweb:1.0.0
          name: kundeweb
          envFrom:
            - configMapRef:
                name: kundeweb-env
          ports:
            # - containerPort: 443
            #   name: https
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 600m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
