---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fahrradweb
  labels:
    app: fahrradweb
spec:
  selector:
    matchLabels:
      app: fahrradweb
  replicas: 1
  template:
    metadata:
      labels:
        app: fahrradweb
    spec:
      serviceAccountName: acme-fahrradweb
      containers:
        - image: docker.io/juergenzimmermann/fahrradweb:1.0.0
          name: fahrradweb
          envFrom:
            - configMapRef:
                name: fahrradweb-env
          ports:
            # - containerPort: 443
            #   name: https
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 600m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
