---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme

configMapGenerator:
  - name: fahrradweb-env
    literals:
      - TZ=Europe/Berlin
      - LANG=de_DE.utf8

commonLabels:
  app.kubernetes.io/component: webserver
  app.kubernetes.io/managed-by: kustomize

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
